### ISSUE TITLE
Con respecto a los riesgos

### ISSUE THREAD

**Issue by rcasalla** [MISO4203-201520/wiki-HotWheels#1]
Hay que definir al menos una acción de mitigación que disminuya la probabilidad que el evento que define el riesgo se cumpla.

**Comment by carmudgeon** [comment]
Si de acuerdo, estamos mejorando ese apartado

**Comment by rcasalla** [comment]
good :)

**Comment by carmudgeon** [comment]
En este momento se incluyen imágenes con los riesgos, si se ven muy pequeños se pueden abrir en otra pestaña del navegador.
